### ISSUE TITLE
IndexOutOfBoundsException in textArea using a custom font

### ISSUE THREAD

**Issue by jpsgamboa** [kotcrab/vis-editor#149] opened 2016-03-23 22:46 UTC
Hey!

Note: I'm using Vis-ui-lml

I'm getting the following error when placing more than one line of text in a text area. Every other widget seems to work fine.

This happens when using any font I generate. Even generating the `VisOpenSansKerned.ttf` provided in raw assets, using the `default.hiero` file provided.

It works fine if I package my skin with the provided `default.fnt` and `default.png` though, so I'm guessing there is something wrong with the way I'm generating the font, since the `.hiero` file doesn't even specify the rendering type (which, by the way I deduce is Java, but I've tried them all).

```
Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: index can't be >= size: 38 >= 15
	at com.badlogic.gdx.utils.FloatArray.get(FloatArray.java:104)
	at com.kotcrab.vis.ui.widget.VisTextField.calculateOffsets(VisTextField.java:247)
	at com.kotcrab.vis.ui.widget.VisTextArea.calculateOffsets(VisTextArea.java:275)
	at com.kotcrab.vis.ui.widget.VisTextField.draw(VisTextField.java:333)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:123)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:163)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:119)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:123)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:163)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:119)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at com.github.czyzby.lml.parser.impl.AbstractLmlView.render(AbstractLmlView.java:45)
	at com.jpsgamboa.trfs.TRFS.render(TRFS.java:40)
	at com.github.czyzby.kiwi.util.gdx.AbstractApplicationListener.render(AbstractApplicationListener.java:23)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```
The `size` 15 always equals the length of the first line I write + 1.
The `index` 38 always equals the length of all the lines I write + 1.
In this case, I'm writing the following to the textArea.
```
        <textArea>
            Text converted
            Text converted line two
        </textArea>
```

Any idea what might be causing this?

**Comment by kotcrab** [comment] 2016-03-23 23:21
This issue might come from libgdx TextField, recently there was some commits that modified `calculateOffsets`. I'll sync VisTextField tomorrow and you will test if that's was the problem. 
It might also come from using multiple threads to modify field text but I doubt you are doing that.

**Comment by jpsgamboa** [comment] 2016-03-24 00:10
Thanks! I'll provide feedback. And no, I'm not using threads since I just put together a little app to try Vis-UI!

**Comment by kotcrab** [comment] 2016-03-24 16:07
So I tried applying libgdx changes but I found quite severe issue in them: https://github.com/libgdx/libgdx/issues/3961 so for now I won't apply them. Let's try to solve this issue without them. 

Can you reproduce this by just using `VisTextArea` directly? Please provide SSCCE and your generated font files. Selected rendering mode in Hiero should not matter for this at all.

**Comment by jpsgamboa** [comment] 2016-03-24 17:43
I created [this](https://github.com/jpsgamboa/VisTest2) test project using `VisTextArea` directly.
Again, works well with VisUI provided font files, but breaks using the font files i generate with the provided `default.hiero`.

It only breaks when it finds a `\n` though, but works fine with long strings. This is also true for my lml test.

The error message is a bit different now:
```
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 28
	at com.kotcrab.vis.ui.widget.VisTextField.calculateOffsets(VisTextField.java:277)
	at com.kotcrab.vis.ui.widget.VisTextArea.calculateOffsets(VisTextArea.java:275)
	at com.kotcrab.vis.ui.widget.VisTextField.draw(VisTextField.java:333)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at com.mygdx.vistest.Main.render(Main.java:43)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

All the raw font files are placed in `assets/raw-font-files`

Note: to run the attached project one must change the working directory to `core/assets`.

**Comment by kotcrab** [comment] 2016-03-25 16:38
Seems to be issue with libgdx, even the fixes from `TextField`/`TextArea` don't help. Btw you are missing input handling in your test:
```java
Gdx.input.setInputProcessor(stage);
//...
stage.act();
```
Sorry, but I should have asked you do this first: try replicating with standard libgdx TextArea and if you succeed report to libgdx. As a workaround you can use `\r` instead of `\n`. You can also try generating font using older version of Hiero. This is the one I'm using for VisUI: [Hiero 3.1](http://dl.kotcrab.com/stuff/hiero3.1.jar)

**Comment by jpsgamboa** [comment] 2016-03-25 19:31
Well I'll be damned.. It works fine with fonts generated with Hiero 3.1.
Unfortunately the font I was trying (Roboto) looks crappy exported from 3.1, with the spacing all messed up. But that's beyond your control.

**Comment by kotcrab** [comment] 2016-04-27 18:58
Any updates on this? Should this issue be closed?

**Comment by jpsgamboa** [comment] 2016-04-27 19:39
Still open in https://github.com/libgdx/libgdx/issues/3887. I guess you can close it since it's on libgdx's end.

**Comment by kotcrab** [comment] 2016-04-27 19:43
Right, I'll leave this open so I won't forget about merging libgdx fixes when https://github.com/libgdx/libgdx/issues/3887 is closed.

**Comment by kotcrab** [comment] 2016-05-06 16:54
This issue still isn't closed in libgdx, but I synced the changes and applied this [fix](https://github.com/libgdx/libgdx/issues/3887#issuecomment-216050150).

@jpsgamboa would be nice if you could verify if this fixes this issue

**Comment by jpsgamboa** [comment] 2016-05-06 18:26
I updated to `1.1.0-SNAPSHOT` but still get the same error:
```
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 49
	at com.kotcrab.vis.ui.widget.VisTextField.calculateOffsets(VisTextField.java:281)
	at com.kotcrab.vis.ui.widget.VisTextArea.calculateOffsets(VisTextArea.java:273)
	at com.kotcrab.vis.ui.widget.VisTextField.draw(VisTextField.java:337)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at com.mygdx.vistest.Main.render(Main.java:43)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

**Comment by kotcrab** [comment] 2016-05-06 19:19
So I get it to run by modifying `VisTextField#updateDiplsayText` to 
```java
		layout.setText(font, displayText);
		glyphPositions.clear();
		float x = 0;
		if (layout.runs.size > 0) {
			GlyphRun run = layout.runs.first();
			fontOffset = run.xAdvances.first();

			for (GlyphRun glyphRun : layout.runs) {
				FloatArray xAdvances = glyphRun.xAdvances;
				for (int i = 1, n = xAdvances.size; i < n; i++) {
					glyphPositions.add(x);
					x += xAdvances.get(i);
				}
			}
		} else
			fontOffset = 0;
		glyphPositions.add(x);
```
(originally it assumes that there is only one GlyphRun)

However after running you example project the font kerning is completely messed up, so I can't commit this fix.
![2016-05-06_2115](https://cloud.githubusercontent.com/assets/4594081/15083808/a9207df2-13cf-11e6-88c3-e0ab9a9d50ef.png)
To be honest I don't understand completely how this new libgdx fonts works but I tried to fix it anyway. Maybe it really is some weird Hiero issue, after all it doesn't happen when using old version.

**Comment by jpsgamboa** [comment] 2016-05-06 19:31
I'll give it a more throughout test later today and give some better feedback. Worst case (for me) is I find some font that works and stick with that, but this problem will return biting other people. Weird thing is how this is not getting much attention from libgdx. Maybe I'll post my case there too. Thank you for your effort!

**Comment by volleybase** [comment] 2016-06-15 17:07
Maybe this is a solution - i am still using visui 0.9.5 and libgdx 1.9.2
I have marked all changings with kgo and vvv before and ^^^ after my addons.

I think there is a problem in ContinueCursor:
    // vvv kgo error correction because of pos+2 in condition below
    linesBreak.ensureCapacity(2);
    // ^^^ kgo error correction
But maybe its only a correction on symptoms, not a real solution - but there is some access to pos + 1 and pos + 2  in an if condition.
-------------------------------------------------------------------------------------------
package x.data.mobile.control;

import com.badlogic.gdx.Input;
import com.badlogic.gdx.graphics.g2d.Batch;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.GlyphLayout;
import com.badlogic.gdx.scenes.scene2d.InputEvent;
import com.badlogic.gdx.scenes.scene2d.InputListener;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.utils.Drawable;
import com.badlogic.gdx.scenes.scene2d.utils.UIUtils;
import com.badlogic.gdx.utils.Align;
import com.badlogic.gdx.utils.IntArray;
import com.badlogic.gdx.utils.Pool;
import com.badlogic.gdx.utils.Pools;
import com.kotcrab.vis.ui.widget.VisTextField;

/**
 * The updated vis text area.<br />
 */
/**
 * A multiple-line text input field, entirely based on {@link TextField}.
 *
 * @author Kotcrab
 * @see TextArea
 */
public class XVisTextArea extends VisTextField {

  /**
   * Array storing lines breaks positions *
   */
  IntArray linesBreak;

  /**
   * Last text processed. This attribute is used to avoid unnecessary
   * computations while calculating offsets *
   */
  private String lastText;

  /**
   * Current line for the cursor *
   */
  int cursorLine;

  /**
   * Index of the first line showed by the text area *
   */
  int firstLineShowing;

  /**
   * Number of lines showed by the text area *
   */
  private int linesShowing;

  /**
   * Variable to maintain the x offset of the cursor when moving up and down. If
   * it's set to -1, the offset is reset *
   */
  float moveOffset;

  private float prefRows;

  // vvv kgo addon (add the X to the constructors)
  public XVisTextArea() {
    super();
  }

  public XVisTextArea(String text, String styleName) {
    super(text, styleName);
  }

  public XVisTextArea(String text, VisTextField.VisTextFieldStyle style) {
    super(text, style);
  }

  public XVisTextArea(String text) {
    super(text);
  }
  // ^^^ kgo addon

  @Override
  protected void initialize() {
    super.initialize();
    writeEnters = true;
    linesBreak = new IntArray();
    cursorLine = 0;
    firstLineShowing = 0;
    moveOffset = -1;
    linesShowing = 0;
  }

  @Override
  protected int letterUnderCursor(float x) {
    if (linesBreak.size > 0) {
      if (cursorLine * 2 >= linesBreak.size) {
        return text.length();
      } else {
        int start = linesBreak.items[cursorLine * 2];
        int end = linesBreak.items[cursorLine * 2 + 1];
        int i = start;
        boolean found = false;
        while (i <= end && !found) {
          if (glyphPositions.items[i] - glyphPositions.items[start] > x) {
            found = true;
          } else {
            i++;
          }
        }
        return Math.max(0, i - 1);
      }
    } else {
      return 0;
    }
  }

  /**
   * Sets the preferred number of rows (lines) for this text area. Used to
   * calculate preferred height
   */
  public void setPrefRows(float prefRows) {
    this.prefRows = prefRows;
  }

  @Override
  public float getPrefHeight() {
    if (prefRows <= 0) {
      return super.getPrefHeight();
    } else {
      float prefHeight = textHeight * prefRows;
      // vvv kgo addon (because style is package internal in VisTextField)
      VisTextField.VisTextFieldStyle style = getStyle();
      // ^^^ kgo addon
      if (style.background != null) {
        prefHeight = Math.max(prefHeight + style.background.getBottomHeight() + style.background.getTopHeight(),
            style.background.getMinHeight());
      }
      return prefHeight;
    }
  }

  /**
   * Returns total number of lines that the text occupies *
   */
  public int getLines() {
    return linesBreak.size / 2 + (newLineAtEnd() ? 1 : 0);
  }

  /**
   * Returns if there's a new line at then end of the text *
   */
  public boolean newLineAtEnd() {
    return text.length() != 0
        && (text.charAt(text.length() - 1) == ENTER_ANDROID || text.charAt(text.length() - 1) == ENTER_DESKTOP);
  }

  /**
   * Moves the cursor to the given number line *
   */
  public void moveCursorLine(int line) {
    if (line < 0) {
      cursorLine = 0;
      cursor = 0;
      moveOffset = -1;
    } else if (line >= getLines()) {
      int newLine = getLines() - 1;
      cursor = text.length();
      if (line > getLines() || newLine == cursorLine) {
        moveOffset = -1;
      }
      cursorLine = newLine;
    } else if (line != cursorLine) {
      if (moveOffset < 0) {
        moveOffset = linesBreak.size <= cursorLine * 2 ? 0 : glyphPositions.get(cursor)
            - glyphPositions.get(linesBreak.get(cursorLine * 2));
      }
      cursorLine = line;
      cursor = cursorLine * 2 >= linesBreak.size ? text.length() : linesBreak.get(cursorLine * 2);
      while (cursor < text.length() && cursor <= linesBreak.get(cursorLine * 2 + 1) - 1
          && glyphPositions.get(cursor) - glyphPositions.get(linesBreak.get(cursorLine * 2)) < moveOffset) {
        cursor++;
      }
      showCursor();
    }
  }

  /**
   * Updates the current line, checking the cursor position in the text *
   */
  void updateCurrentLine() {
    int index = calculateCurrentLineIndex(cursor);
    int line = index / 2;
    // Special case when cursor moves to the beginning of the line from the end of another and a word
    // wider than the box
    if (index % 2 == 0 || index + 1 >= linesBreak.size || cursor != linesBreak.items[index]
        || linesBreak.items[index + 1] != linesBreak.items[index]) {
      if (line < linesBreak.size / 2 || text.length() == 0 || text.charAt(text.length() - 1) == ENTER_ANDROID
          || text.charAt(text.length() - 1) == ENTER_DESKTOP) {
        cursorLine = line;
      }
    }
  }

  /**
   * Scroll the text area to show the line of the cursor *
   */
  void showCursor() {
    updateCurrentLine();
    if (cursorLine != firstLineShowing) {
      int step = cursorLine >= firstLineShowing ? 1 : -1;
      while (firstLineShowing > cursorLine || firstLineShowing + linesShowing - 1 < cursorLine) {
        firstLineShowing += step;
      }
    }
  }

  /**
   * Calculates the text area line for the given cursor position *
   */
  private int calculateCurrentLineIndex(int cursor) {
    int index = 0;
    while (index < linesBreak.size && cursor > linesBreak.items[index]) {
      index++;
    }
    return index;
  }

  // OVERRIDE from TextField
  @Override
  protected void sizeChanged() {
    lastText = null; // Cause calculateOffsets to recalculate the line breaks.

    // vvv kgo addon (because style is package internal in VisTextField)
    VisTextField.VisTextFieldStyle style = getStyle();
    // ^^^ kgo addon
    // The number of lines showed must be updated whenever the height is updated
    BitmapFont font = style.font;
    Drawable background = style.background;
    float availableHeight = getHeight() - (background == null ? 0 : background.getBottomHeight() + background.getTopHeight());
    linesShowing = (int) Math.floor(availableHeight / font.getLineHeight());
  }

  @Override
  protected float getTextY(BitmapFont font, Drawable background) {
    float textY = getHeight();
    if (background != null) {
      textY = (int) (textY - background.getTopHeight());
    }
    return textY;
  }

  @Override
  protected void drawSelection(Drawable selection, Batch batch, BitmapFont font, float x, float y) {
    int i = firstLineShowing * 2;
    float offsetY = 0;
    int minIndex = Math.min(cursor, selectionStart);
    int maxIndex = Math.max(cursor, selectionStart);
    while (i + 1 < linesBreak.size && i < (firstLineShowing + linesShowing) * 2) {

      int lineStart = linesBreak.get(i);
      int lineEnd = linesBreak.get(i + 1);

      if (!((minIndex < lineStart && minIndex < lineEnd && maxIndex < lineStart && maxIndex < lineEnd) || (minIndex > lineStart
          && minIndex > lineEnd && maxIndex > lineStart && maxIndex > lineEnd))) {

        int start = Math.max(linesBreak.get(i), minIndex);
        int end = Math.min(linesBreak.get(i + 1), maxIndex);

        float selectionX = glyphPositions.get(start) - glyphPositions.get(linesBreak.get(i));
        float selectionWidth = glyphPositions.get(end) - glyphPositions.get(start);

        selection.draw(batch, x + selectionX + fontOffset, y - textHeight - font.getDescent() - offsetY, selectionWidth,
            font.getLineHeight());
      }

      offsetY += font.getLineHeight();
      i += 2;
    }
  }

  @Override
  protected void drawText(Batch batch, BitmapFont font, float x, float y) {
    float offsetY = 0;
    for (int i = firstLineShowing * 2; i < (firstLineShowing + linesShowing) * 2 && i < linesBreak.size; i += 2) {
      font.draw(batch, displayText, x, y + offsetY, linesBreak.items[i], linesBreak.items[i + 1], 0, Align.left, false);
      offsetY -= font.getLineHeight();
    }
  }

  @Override
  protected void drawCursor(Drawable cursorPatch, Batch batch, BitmapFont font, float x, float y) {
    float textOffset = cursor >= glyphPositions.size || cursorLine * 2 >= linesBreak.size ? 0 : glyphPositions.get(cursor)
        - glyphPositions.get(linesBreak.items[cursorLine * 2]);
    cursorPatch.draw(batch, x + textOffset + fontOffset + font.getData().cursorX, y - font.getDescent() / 2
        - (cursorLine - firstLineShowing + 1) * font.getLineHeight(), cursorPatch.getMinWidth(), font.getLineHeight());
  }

  @Override
  protected void calculateOffsets() {
    super.calculateOffsets();
    if (!this.text.equals(lastText)) {
      this.lastText = text;
      // vvv kgo addon (because style is package internal in VisTextField)
      VisTextField.VisTextFieldStyle style = getStyle();
      // ^^^ kgo addon
      BitmapFont font = style.font;
      float maxWidthLine = this.getWidth()
          - (style.background != null ? style.background.getLeftWidth() + style.background.getRightWidth() : 0);
      linesBreak.clear();
      int lineStart = 0;
      int lastSpace = 0;
      char lastCharacter;
      Pool<GlyphLayout> layoutPool = Pools.get(GlyphLayout.class);
      GlyphLayout layout = layoutPool.obtain();
      for (int i = 0; i < text.length(); i++) {
        lastCharacter = text.charAt(i);
        if (lastCharacter == ENTER_DESKTOP || lastCharacter == ENTER_ANDROID) {
          linesBreak.add(lineStart);
          linesBreak.add(i);
          lineStart = i + 1;
        } else {
          lastSpace = (continueCursor(i, 0) ? lastSpace : i);
          layout.setText(font, text.subSequence(lineStart, i + 1));
          if (layout.width > maxWidthLine) {
            if (lineStart >= lastSpace) {
              lastSpace = i - 1;
            }
            linesBreak.add(lineStart);
            linesBreak.add(lastSpace + 1);
            lineStart = lastSpace + 1;
            lastSpace = lineStart;
          }
        }
      }
      layoutPool.free(layout);
      // Add last line
      if (lineStart < text.length()) {
        linesBreak.add(lineStart);
        linesBreak.add(text.length());
      }
      showCursor();
    }
  }

  @Override
  protected InputListener createInputListener() {
    return new TextAreaListener();
  }

  @Override
  public void setSelection(int selectionStart, int selectionEnd) {
    super.setSelection(selectionStart, selectionEnd);
    updateCurrentLine();
  }

  @Override
  protected void moveCursor(boolean forward, boolean jump) {
    int count = forward ? 1 : -1;
    int index = (cursorLine * 2) + count;
    if (index >= 0 && index + 1 < linesBreak.size && linesBreak.items[index] == cursor && linesBreak.items[index + 1] == cursor) {
      cursorLine += count;
      if (jump) {
        super.moveCursor(forward, jump);
      }
      showCursor();
    } else {
      super.moveCursor(forward, jump);
    }
    updateCurrentLine();

  }

  @Override
  protected boolean continueCursor(int index, int offset) {
    int pos = calculateCurrentLineIndex(index + offset);
    // vvv kgo error correction because of pos+2 in condition below
    linesBreak.ensureCapacity(2);
    // ^^^ kgo error correction
    return super.continueCursor(index, offset)
        && (pos < 0 || pos >= linesBreak.size || (linesBreak.items[pos + 1] != index) || (linesBreak.items[pos + 1] == linesBreak.items[pos + 2]));
  }

  public int getCursorLine() {
    return cursorLine;
  }

  public int getFirstLineShowing() {
    return firstLineShowing;
  }

  public int getLinesShowing() {
    return linesShowing;
  }

  /**
   * Input listener for the text area *
   */
  public class TextAreaListener extends VisTextField.TextFieldClickListener {

    @Override
    protected void setCursorPosition(float x, float y) {
      moveOffset = -1;

      // vvv kgo addon (because style is package internal in VisTextField)
      VisTextField.VisTextFieldStyle style = getStyle();
      // ^^^ kgo addon
      Drawable background = style.background;
      BitmapFont font = style.font;

      float height = getHeight();

      if (background != null) {
        height -= background.getTopHeight();
        x -= background.getLeftWidth();
      }
      x = Math.max(0, x);
      if (background != null) {
        y -= background.getTopHeight();
      }

      cursorLine = (int) Math.floor((height - y) / font.getLineHeight()) + firstLineShowing;
      cursorLine = Math.max(0, Math.min(cursorLine, getLines() - 1));

      super.setCursorPosition(x, y);
      updateCurrentLine();
    }

    @Override
    public boolean keyDown(InputEvent event, int keycode) {
      super.keyDown(event, keycode);
      Stage stage = getStage();
      // vvv kgo addon (add the X to the this modifier)
      if (stage != null && stage.getKeyboardFocus() == XVisTextArea.this) {
        // ^^^ kgo addon
        boolean repeat = false;
        boolean shift = UIUtils.shift();
        if (keycode == Input.Keys.DOWN) {
          if (shift) {
            if (!hasSelection) {
              selectionStart = cursor;
              hasSelection = true;
            }
          } else {
            clearSelection();
          }
          moveCursorLine(cursorLine + 1);
          repeat = true;

        } else if (keycode == Input.Keys.UP) {
          if (shift) {
            if (!hasSelection) {
              selectionStart = cursor;
              hasSelection = true;
            }
          } else {
            clearSelection();
          }
          moveCursorLine(cursorLine - 1);
          repeat = true;

        } else {
          moveOffset = -1;
        }
        if (repeat) {
          scheduleKeyRepeatTask(keycode);
        }
        showCursor();
        return true;
      }
      return false;
    }

    @Override
    public boolean keyTyped(InputEvent event, char character) {
      boolean result = super.keyTyped(event, character);
      showCursor();
      return result;
    }

    @Override
    protected void goHome(boolean jump) {
      if (jump) {
        cursor = 0;
      } else if (cursorLine * 2 < linesBreak.size) {
        cursor = linesBreak.get(cursorLine * 2);
      }
    }

    @Override
    protected void goEnd(boolean jump) {
      if (jump || cursorLine >= getLines()) {
        cursor = text.length();
      } else if (cursorLine * 2 + 1 < linesBreak.size) {
        cursor = linesBreak.get(cursorLine * 2 + 1);
      }
    }
  }
}

Please check it, and if its ok, please use it or send it to libgdx...

**Comment by kotcrab** [comment] 2016-06-20 20:32
Sorry, I checked notification on my phone and forgot about this issue... I'll check your fix tomorrow.

**Comment by kotcrab** [comment] 2016-06-21 10:00
@volleybase this doesn't work for this issue (`java.lang.ArrayIndexOutOfBoundsException: 28`), I think your fix is meant for https://github.com/libgdx/libgdx/issues/3887. Somebody already created PR https://github.com/libgdx/libgdx/pull/4160 for it which looks like an actual fix.

The original issue with index of out bounds is still unfixed, even in the newest libGDX `1.9.4-SNAPSHOT` using standard `TextArea`. Your best bet is to report it in libgdx repository since I don't know how to fix it.

**Comment by volleybase** [comment] 2016-07-21 12:32
I don't know if I'm right or wrong, but I have another try to fix that problem in VisTextArea/VisTextField.
Situation: VisTextArea with custom font
VisTextArea uses many functions of VisTextField - one is updateDisplayText. There you collect the glyphPositions from layout.runs, but only from layout.runs.first()!
Now I try to read all glyphruns -> please check it and use it if it is ok!

    layout.setText(font, displayText);
    glyphPositions.clear();
    float x = 0;
    if (layout.runs.size > 0) {
      // vvv ### !!!
      //GlyphLayout.GlyphRun run = layout.runs.first();
      Iterator<GlyphRun> iter = layout.runs.iterator();
      while (iter.hasNext()) {
        GlyphRun run = iter.next();

        FloatArray xAdvances = run.xAdvances;
        fontOffset = xAdvances.first();
        for (int i = 1, n = xAdvances.size; i < n; i++) {
          glyphPositions.add(x);
          x += xAdvances.get(i);
        }

        // add position of line break
        glyphPositions.add(x);
      }
      // ^^^ ### !!!

    } else {
      fontOffset = 0;
    }
    glyphPositions.add(x);

**Comment by volleybase** [comment] 2016-07-21 12:41
I've seen the same code in TextField (libgdx), but I haven't tested -> I think that might be the same problem... If my fix is correct, please send them the update, too.
Thanks for your work, I like it very much.

**Comment by kotcrab** [comment] 2016-07-22 09:01
@volleybase yeah this is pretty much the same as my fix from https://github.com/kotcrab/vis-editor/issues/149#issuecomment-217535144 but as you can see it resulted in messed font kerning (see screenshot). But I checked it again and this isn't actually VisUI/scene2d issue. If I render the same text using plain old `BitmapFont#draw` I get the same results. Looks like Hiero is messing up kerning data from font. If that's the cause I'll be using that code as a fix for this issue. Thanks!

![2016-07-22_1045](https://cloud.githubusercontent.com/assets/4594081/17051542/948232bc-4ff9-11e6-930d-57beb63eb5d2.png)

**Closed** 2016-07-22 09:01 UTC
Labels: bug, ui

**Comment by volleybase** [comment] 2016-07-28 08:32
A first idea for the problem with the characters:
With some heights of the textarea the last line is ok:
![2nd line is ok](https://cloud.githubusercontent.com/assets/13930766/17205665/2f6cb8cc-54ac-11e6-8119-1726c06fd89c.png)
But with other heights of the textarea it is not ok:
![2nd line is not ok](https://cloud.githubusercontent.com/assets/13930766/17205718/6ab7852e-54ac-11e6-86ae-13a3a98f7965.png)

Only the vertical positions seems to be ok.
Its just an info, not a solution, but maybe it can help someone on solving the problem.
My font in the images is Overpass-Regular.ttf, prepared with hiero, size 32, distance field, scaled down to 0.5.
