### ISSUE TITLE
X2 UI is not enough for mobile

### ISSUE THREAD

**Issue by jduke32** [kotcrab/vis-editor#263] opened 2017-08-30 19:51 UTC
Hello , i have tried X2 but its not enough for mobile.Especially
FileChooser cant be seen on android devices.

VisUI.load( VisUI.SkinScale.X2 );

How can i make more scale like X4  ?

**Comment by kotcrab** [comment] 2017-08-30 21:07
Duplicate of https://github.com/kotcrab/vis-editor/issues/226

`FileChooser` is a desktop platform only widget. You can't use it on Android.

**Closed by kotcrab** 2017-08-30 21:07 UTC
Labels: duplicate, ui
