### ISSUE TITLE
VisTextArea throws java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-editor#177] opened 2016-05-06 16:24 UTC
This exception can be thrown by the `VisTextArea`:
> Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 16
> 	at com.kotcrab.vis.ui.widget.VisTextArea.continueCursor(VisTextArea.java:348)
> 	at com.kotcrab.vis.ui.widget.VisTextArea.calculateOffsets(VisTextArea.java:294)
> 	at com.kotcrab.vis.ui.widget.VisTextField.draw(VisTextField.java:334)
> 	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
> 	at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.draw(ScrollPane.java:588)
> 	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:123)
> 	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
> 	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:163)
> 	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:119)
> 	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
> 	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:110)
> 	at com.badlogic.gdx.scenes.scene2d.ui.Window.draw(Window.java:245)
> 	at com.kotcrab.vis.ui.widget.VisWindow.draw(VisWindow.java:216)
> 	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
> 	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
> 	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
> 	at com.github.czyzby.autumn.mvc.component.ui.controller.impl.StandardViewRenderer.render(StandardViewRenderer.java:13)
> 	at com.github.czyzby.autumn.mvc.component.ui.controller.impl.AnnotatedViewController.render(AnnotatedViewController.java:165)
> 	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.render(InterfaceService.java:479)
> 	at com.github.czyzby.autumn.mvc.application.AutumnApplication.render(AutumnApplication.java:139)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

The first time when it occurred, area contained text with Polish characters, so I assumed this was the source of error. I modified the message and it started to work as expected.

However, the second time it was a stack trace without any special characters. It's worth noting that both times the last character was `\n`.

EDIT: after I removed the last `\n`, the error still occurred when I appended stack trace to the text area. However, the exception occurrence seems highly dependent on the input: when I slightly modified the way stack trace is appended (basically added `- at` prefix before each line), the error was no longer thrown.

**Comment by kotcrab** [comment] 2016-05-06 16:53
I've synced changes from libgdx `TextArea` and `TextField`, I'm afraid this is all I can do without SSCCE or chance to reliably reproduce this. Those changes modify `continueCursor` so it *may* fix it.

**Comment by czyzby** [comment] 2016-05-06 17:02
It doesn't seem to be thrown for the same data as before, but when I tried to copy the whole content (to post the data to reproduce this), this exception was thrown:

> Exception in thread "LWJGL Application" java.lang.StringIndexOutOfBoundsException: String index out of range: 374
> 	at java.lang.String.substring(String.java:1963)
> 	at com.kotcrab.vis.ui.widget.VisTextField.copy(VisTextField.java:460)
> 	at com.kotcrab.vis.ui.widget.VisTextField$TextFieldClickListener.keyDown(VisTextField.java:1032)
> 	at com.kotcrab.vis.ui.widget.VisTextArea$TextAreaListener.keyDown(VisTextArea.java:402)
> 	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:45)
> 	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
> 	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
> 	at com.badlogic.gdx.scenes.scene2d.Stage.keyDown(Stage.java:417)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:312)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
> 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

**Comment by kotcrab** [comment] 2016-05-06 17:07
Can this be reproduced with standard `TextArea`? And more importantly can you provide SSCCE?

**Comment by czyzby** [comment] 2016-05-06 17:11
Not sure, I'll try preparing a simple application in a separate project.

**Comment by czyzby** [comment] 2016-05-06 17:22
Try running this sample:
```
public class MainClass extends ApplicationAdapter {
    private Stage stage;

    @Override
    public void create() {
        VisUI.load(SkinScale.X1);

        stage = new Stage(new ScreenViewport());
        Gdx.input.setInputProcessor(stage);

        final VisTextArea area = new VisTextArea(
                "Preparing the project...\nProject files copied.\nThe project is ready. In most modern IDEs you can import it as a Gradle project. Useful Gradle tasks:\n- idea - generates IntelliJ project\n- eclipse - generates Eclipse project\n- pack - packs GUI atlas (if GUI assets generation was chosen in advanced tab)\n- desktop:run - runs the desktop application.\n- gwt:superDev - compiles GWT application and allows you to debug it at localhost:8080/gwt",
                "small");

        final VisWindow window = new VisWindow("example window");
        window.add("this is a simple VisUI window").padTop(5f).row();
        window.add(area).minSize(300).pad(10f);
        window.pack();
        window.centerWindow();
        stage.addActor(window.fadeIn());
    }

    @Override
    public void resize(final int width, final int height) {
        stage.getViewport().update(width, height);
    }

    @Override
    public void render() {
        Gdx.gl.glClearColor(0f, 0f, 0f, 1f);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        stage.act(Math.min(Gdx.graphics.getDeltaTime(), 1 / 30f));
        stage.draw();
    }

    @Override
    public void dispose() {
        VisUI.dispose();
        stage.dispose();
    }
}
```
Select the whole text, starting from right bottom corner. Copy it with `CTRL + C`.

**Comment by kotcrab** [comment] 2016-05-06 17:29
Thanks for the sample, I can reproduce it now. This may be somewhat related to other issue with cursor. If there is more text than can fix in `VisTextArea` and you try to select it, cursor can be drawn outside text area (but not outside Window due to clipping), seems to also happen in standard `TextArea`.

**Comment by kotcrab** [comment] 2016-05-06 18:24
I fixed `letterUnderCursor` and added clamps for `#copy()`. Cursor can still be drawn outside text area though.

**Comment by czyzby** [comment] 2016-05-06 18:26
I think that visual bugs (as annoying as they are) are still less important than functionality-related bugs that can crash your application. ; ) Thanks for the fix.

**Comment by kotcrab** [comment] 2016-05-06 18:45
> I think that visual bugs (as annoying as they are) are still less important than functionality-related bugs that can crash your application.

Sure. I'm not going to fix this. For very simple workaround you can put text area inside Table with clipping enabled. Closing this.

**Closed by kotcrab** 2016-05-06 18:45 UTC
Labels: bug, ui
